#!/bin/bash

# 2024-10-09
# search
# Farah Noor
# Database Unix Prog
# Purpose: To search a medication list and produce a report as requested by user.
#
# I certify that the program and code are my own work.
#
# I did not use generative AI.

while true
do
  echo -n 'Enter Medication Code? '
  read givenCode
  if [ $givenCode = "ZZZ" ]
  then
    break
  fi
  echo -n 'See Generic Name (G/g) or Dose (D/d)? '
  read nameOrDose
  until [ $nameOrDose = "G" -o $nameOrDose = "g" -o $nameOrDose = "D" -o $nameOrDose = "d" ]
  do
    echo 'Please enter only G or D.'
    echo -n 'See Generic Name (G/g) or Dose (D/d)? '
    read nameOrDose
  done
  exists=false
  while read line
  do
    medicationCode=${line:18:8}
    if [[ "$medicationCode" ==  *"$givenCode"* ]]
    then
      if [ $nameOrDose = "G" -o $nameOrDose = "g" ]
      then
        genericName=${line:26:13}
        echo "$medicationCode : $genericName"
        exists=true
      fi
      if [ $nameOrDose = "D" -o $nameOrDose = "d" ]
      then
        dose=${line:4:14}
        echo "$medicationCode : $dose"
        exists=true
      fi
    fi
  done < ~lhiraki/open/ccps393/medslist
  if [ $exists = "false" ]
  then
    echo 'No such Medication Code. '
  fi
done
echo "Goodbye."

